volumes:
  auth_data:
  redis_data:
  orgs_data:
  commands_queue_data:
  connector_data:

networks:
  auth-net:
    driver: bridge
  orgs-net:
    driver: bridge
  connector-net:
    driver: bridge

services:
  # COMMANDS QUEUE
  rabbit-mq:
    image: "rabbitmq:latest"
    env_file:
      - ./env/rabbitmq.env # exampe only
    ports:
      - 5672:5672
    volumes:
      - commands_queue_data:/var/lib/rabbitmq
  # CONNECTOR SERVICE
  connector:
    restart: unless-stopped
    depends_on:
      - connector-database
      - rabbit-mq
    build: https://git@git.sourcecraft.dev/organization-shipmonitor/ship-cloud-connector.git
    ports:
      - 8070:8070
      - 8071:8071
    networks:
      - connector-net
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbit-mq:5672/
      PORT: 8070
      DATABASE_CONNECTION_STRING: "host='cloud-connector-database' user='connector' password='CoolPassword123' port='5432' dbname='connector-db' sslmode=disable"
      DATABASE_AUTO_MIGRATE: true
  # Connector database
  connector-database:
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "CoolPassword123"
      POSTGRES_USER: "connector"
      POSTGRES_DB: "connector-db"
    networks:
      - connector-net
    volumes:
      - connector_data:/var/lib/postgresql/data/
  # AUTH SERVICE
  auth-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@auth-db:5432/postgres?sslmode=disable
      SECURITY_KEY: "your_jwt_security_key_here"
      SPICEDB_ADDRESS: spice:50051
      SPICEDB_API_KEY: somerandomkey
    depends_on:
      - auth-db
      - spice
    networks:
      - auth-net
  # AUTH SERVICE DATABASE
  auth-db:
    networks:
      - auth-net
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - auth_data:/var/lib/postgresql/data
  # SPICE for permissions
  spice:
    image: quay.io/authzed/spicedb:latest
    depends_on:
      - auth-db
      - spice-migrate
    restart: unless-stopped
    command: serve
    ports:
      - "50051:50051"
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: somerandomkey
      SPICEDB_LOG_LEVEL: debug
      SPICEDB_DATASTORE_ENGINE: postgres
      SPICEDB_DATASTORE_CONN_URI: postgres://postgres:postgres@auth-db:5432/postgres?sslmode=disable
    networks:
      - auth-net
  # SPICE MIGRATION
  spice-migrate:
    image: quay.io/authzed/spicedb:latest
    depends_on:
      - auth-db
    command: migrate head
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: somerandomkey
      SPICEDB_LOG_LEVEL: debug
      SPICEDB_DATASTORE_ENGINE: postgres
      SPICEDB_DATASTORE_CONN_URI: postgres://postgres:postgres@auth-db:5432/postgres?sslmode=disable
    networks:
      - auth-net
  # orgs-api:
  #   restart: unless-stopped
  #   build: https://git@git.sourcecraft.dev/organization-shipmonitor/ship-cloud-organizations.git
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     PORT: 8080
  #     DB_CONNECTION_STRING: postgres://postgres:postgres@orgs-db:5432/postgres?sslmode=disable
  #     JWT_SECURITY_KEY: "your_jwt_security_key_here"
  #   depends_on:
  #     - orgs-db
  #     - auth-api
  #   networks:
  #     - orgs-net
  # orgs-db:
  #   networks:
  #     - orgs-net
  #   image: postgres:18
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #     PGDATA: /var/lib/postgresql/data
  #   volumes:
  #     - orgs_data:/var/lib/postgresql/data
